apiVersion: v1
kind: ConfigMap
metadata:
  name: client-cli2
  namespace: kafka
data:
  create_cert.sh: |
    #!/bin/sh

    echo "starting"

    TRUST_PASS=$(cat /user/app/ca-cert/ca.password)

    echo "
    security.protocol=SSL
    ssl.truststore.location=/user/app/ca-cert/ca.p12
    ssl.truststore.password=$TRUST_PASS
    ssl.truststore.type=PKCS12
    " > /tmp/client.properties
