apiVersion: v1
kind: Pod
metadata:
  labels:
    app: kafka-cli
  name: kafka-cli
spec:
  containers:
    - name: kafka-cli
      command: 
        - /bin/sh
        - '-c'
        - tail -f /dev/null
      image: confluentinc/cp-kafka-connect:7.3.1
      volumeMounts: 
       - name: kafka-certs-cluster-ca-cert
         mountPath: /user/app/ca-cert
       - name: kafka-certs-kafka-cli
         mountPath: /user/app/ca-cli
       - name: config-volume
         mountPath: /user/app/config
      env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: kafka-certs-kafka-bootstrap:9093
  volumes:
    - name: kafka-certs-cluster-ca-cert
      secret:
        secretName: kafka-certs-cluster-ca-cert
    - name: kafka-certs-kafka-cli
      secret:
        secretName: kafka-cli
    - name: config-volume
      configMap:
        name: client-cli