# rolebinding.yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: RoleBinding1
  namespace: kafka
subjects:
- kind: ServiceAccount
  name: KafkaServiceAccount1
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: KafkaRole1
  apiGroup: rbac.authorization.k8s.io
