apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: teste2
  labels:
    strimzi.io/cluster: kafka-certs
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
