apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaUser
metadata:
  name: kafka-cli
  labels:
    strimzi.io/cluster: kafka-certs
spec:
  authentication:
    type: tls
  # authorization:
  #   type: simple
  #   acls:
  #     - host: '*'
  #       operations:
  #         - All
  #       resource:
  #         type: topic
  #         name: '*'
  #         patternType: literal
  #     - host: '*'
  #       operations:
  #         - All
  #       resource:
  #         type: group
  #         name: '*'
  #         patternType: literal
  #     - host: '*'
  #       operations:
  #         - All
  #       resource:
  #         type: transactionalId
  #         name: '*'
  #         patternType: literal  
          